[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "protocol/=../protocol/Backend_Lending---Borrowing/contracts/"
]
fs_permissions = [{ access = "read", path = "../protocol/Backend_Lending---Borrowing" }]

[profile.default.invariant]
runs = 128
depth = 500


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
